# Generated by Django 4.2.3 on 2024-01-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='thumbnail_height',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='stories',
            name='thumbnail_width',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='stories',
            name='news',
            field=models.CharField(max_length=255),
        ),
    ]
