# Generated by Django 4.2.3 on 2024-01-12 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_stories_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='link',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='thumbnail_height',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='thumbnail_width',
        ),
    ]
